//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckWatcher.DbProxyReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbProxyReference.IDbProxy")]
    public interface IDbProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbProxy/TakeCheque", ReplyAction="http://tempuri.org/IDbProxy/TakeChequeResponse")]
        void TakeCheque(CheckWorker.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbProxy/TakeCheque", ReplyAction="http://tempuri.org/IDbProxy/TakeChequeResponse")]
        System.Threading.Tasks.Task TakeChequeAsync(CheckWorker.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbProxy/GetCheques", ReplyAction="http://tempuri.org/IDbProxy/GetChequesResponse")]
        CheckWorker.Cheque[] GetCheques(int howMany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbProxy/GetCheques", ReplyAction="http://tempuri.org/IDbProxy/GetChequesResponse")]
        System.Threading.Tasks.Task<CheckWorker.Cheque[]> GetChequesAsync(int howMany);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbProxyChannel : CheckWatcher.DbProxyReference.IDbProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbProxyClient : System.ServiceModel.ClientBase<CheckWatcher.DbProxyReference.IDbProxy>, CheckWatcher.DbProxyReference.IDbProxy {
        
        public DbProxyClient() {
        }
        
        public DbProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TakeCheque(CheckWorker.Cheque cheque) {
            base.Channel.TakeCheque(cheque);
        }
        
        public System.Threading.Tasks.Task TakeChequeAsync(CheckWorker.Cheque cheque) {
            return base.Channel.TakeChequeAsync(cheque);
        }
        
        public CheckWorker.Cheque[] GetCheques(int howMany) {
            return base.Channel.GetCheques(howMany);
        }
        
        public System.Threading.Tasks.Task<CheckWorker.Cheque[]> GetChequesAsync(int howMany) {
            return base.Channel.GetChequesAsync(howMany);
        }
    }
}
